install.packages(
  c(
    "gapminder",
    "ggforce",
    "gh",
    "globals",
    "openintro",
    "profvis",
    "RSQLite",
    "shiny",
    "shinycssloaders",
    "shinyFeedback",
    "shinythemes",
    "testthat",
    "thematic",
    "tidyverse",
    "vroom",
    "waiter",
    "xml2",
    "zeallot"
  )
)